### ISSUE TITLE
Every Link in the Portlet initiates a full Page request

### ISSUE THREAD

**Issue by pdimitri** [nonblocking/liferay-angularjs-portlet#1]
I've got the Portlet working, and deployed it to a Liferay 6.2 EE Server. Whenever I click on any Link in the Portlet, a full Page Request to "/#" is submitted to the Server, resulting in a Page reload, which in turn resets the Portlet to it's inital state (showing the first page of the User List). For Instance when clicking on the Details Link of any User, the Users Details Page shows up for a second, until the Page reloads and the User List is shown again. Even worse: When the Portlet has been placed on any other Page then the Sites default Page, after clicking on a Link in the Portlet the Page changes to the Sites default Page.

Links should be changed to be i.e.:

`<a href ng-click="showDetails(user.userId)">Details</a>`

Instead of

`<a href="#" ng-click="showDetails(user.userId)">Details</a>`

**Comment by koflerju** [comment]
Fixed.
